# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Zadanie2
                                 A QGIS plugin
 Liczenie przewyższeń oraz pól
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-11
        copyright            : (C) 2023 by AKRS
        email                : r.szlen5320@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Zadanie2 class from file Zadanie2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Zadanie_Drugie import Zadanie2
    return Zadanie2(iface)
