# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zadanie_Drugie_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zadanie2DialogBase(object):
    def setupUi(self, Zadanie2DialogBase):
        Zadanie2DialogBase.setObjectName("Zadanie2DialogBase")
        Zadanie2DialogBase.resize(659, 428)
        self.button_box = QtWidgets.QDialogButtonBox(Zadanie2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(80, 390, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.licz_pole = QtWidgets.QPushButton(Zadanie2DialogBase)
        self.licz_pole.setGeometry(QtCore.QRect(390, 130, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.licz_pole.setFont(font)
        self.licz_pole.setObjectName("licz_pole")
        self.licz_przew = QtWidgets.QPushButton(Zadanie2DialogBase)
        self.licz_przew.setGeometry(QtCore.QRect(60, 130, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.licz_przew.setFont(font)
        self.licz_przew.setObjectName("licz_przew")
        self.mMapLayerComboBox = QgsMapLayerComboBox(Zadanie2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(280, 30, 191, 41))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label_3 = QtWidgets.QLabel(Zadanie2DialogBase)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.okno_wynikowe = QtWidgets.QTextEdit(Zadanie2DialogBase)
        self.okno_wynikowe.setGeometry(QtCore.QRect(100, 250, 481, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.okno_wynikowe.setFont(font)
        self.okno_wynikowe.setObjectName("okno_wynikowe")
        self.line = QtWidgets.QFrame(Zadanie2DialogBase)
        self.line.setGeometry(QtCore.QRect(10, 90, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Zadanie2DialogBase)
        self.line_2.setGeometry(QtCore.QRect(330, 100, 20, 131))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Zadanie2DialogBase)
        self.line_3.setGeometry(QtCore.QRect(10, 205, 641, 51))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(Zadanie2DialogBase)
        self.button_box.accepted.connect(Zadanie2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Zadanie2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Zadanie2DialogBase)

    def retranslateUi(self, Zadanie2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Zadanie2DialogBase.setWindowTitle(_translate("Zadanie2DialogBase", "Zad2"))
        self.licz_pole.setText(_translate("Zadanie2DialogBase", "Licz pole powierzchni [m^2]"))
        self.licz_przew.setText(_translate("Zadanie2DialogBase", "Licz przewyższenie [m]"))
        self.label_3.setText(_translate("Zadanie2DialogBase", "Wybierz warstwe:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
